name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install dependenices
      run: npm install
    - name: Start the application
      run: npm run start &
    - name: Install playwright
      run: npx playwright install
    - name: Execute UI Tests
      run: npm run test-ui
